# Generated by Django 5.2.6 on 2025-10-01 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(choices=[('red', 'Vermelho'), ('blue', 'Azul'), ('green', 'Verde'), ('black', 'Preto'), ('white', 'Branco'), ('yellow', 'Amarelo'), ('pink', 'Rosa'), ('purple', 'Roxo'), ('orange', 'Laranja'), ('gray', 'Cinza')], default='black', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('XS', 'Extra Pequeno'), ('S', 'Pequeno'), ('M', 'Médio'), ('L', 'Grande'), ('XL', 'Extra Grande'), ('XXL', 'Extra Extra Grande')], default='M', max_length=10),
        ),
    ]
