# Generated by Django 5.2.6 on 2025-10-18 19:59

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_store_order_store_product_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=100, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('color', models.CharField(blank=True, choices=[('red', 'Vermelho'), ('blue', 'Azul'), ('green', 'Verde'), ('black', 'Preto'), ('white', 'Branco'), ('yellow', 'Amarelo'), ('pink', 'Rosa'), ('purple', 'Roxo'), ('orange', 'Laranja'), ('gray', 'Cinza')], max_length=20, null=True)),
                ('size', models.CharField(blank=True, choices=[('XS', 'Extra Pequeno'), ('S', 'Pequeno'), ('M', 'Médio'), ('L', 'Grande'), ('XL', 'Extra Grande'), ('XXL', 'Extra Extra Grande')], max_length=10, null=True)),
                ('stock', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/variants/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='sales.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='orderitem',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='sales.productvariant'),
        ),
    ]
