# Generated by Django 5.2.6 on 2025-10-21 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_alter_product_sku_productvariant_orderitem_variant'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStatusUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('note', models.TextField(blank=True, default='')),
                ('is_automatic', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('online', 'Online'), ('cod', 'Pagamento na entrega')], default='online', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('paid', 'Pago'), ('failed', 'Falhou')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='model',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('processing', 'Processando'), ('awaiting_delivery', 'Aguardando entrega'), ('out_for_delivery', 'Saiu para entrega'), ('delivered', 'Entregue'), ('cancelled', 'Cancelado'), ('shipped', 'Enviado')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('XS', 'Extra Pequeno'), ('S', 'Pequeno'), ('M', 'Médio'), ('L', 'Grande'), ('XL', 'Extra Grande'), ('XXL', 'Extra Extra Grande'), ('33', '33'), ('34', '34'), ('35', '35'), ('36', '36'), ('37', '37'), ('38', '38'), ('39', '39'), ('40', '40'), ('41', '41'), ('42', '42'), ('43', '43'), ('44', '44'), ('45', '45')], default='M', max_length=10),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='size',
            field=models.CharField(blank=True, choices=[('XS', 'Extra Pequeno'), ('S', 'Pequeno'), ('M', 'Médio'), ('L', 'Grande'), ('XL', 'Extra Grande'), ('XXL', 'Extra Extra Grande'), ('33', '33'), ('34', '34'), ('35', '35'), ('36', '36'), ('37', '37'), ('38', '38'), ('39', '39'), ('40', '40'), ('41', '41'), ('42', '42'), ('43', '43'), ('44', '44'), ('45', '45')], max_length=10, null=True),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.UniqueConstraint(condition=models.Q(('color__isnull', False), ('size__isnull', False), ('model__isnull', False)), fields=('product', 'color', 'size', 'model'), name='uniq_product_color_size_model'),
        ),
        migrations.AddField(
            model_name='orderstatusupdate',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_updates', to='sales.order'),
        ),
    ]
