# Generated by Django 5.2.6 on 2025-10-30 02:33

from django.db import migrations


def migrate_products_to_variants(apps, schema_editor):
    """
    Create default variants for products that don't have any.
    This ensures all products have at least one variant with price/stock.
    """
    Product = apps.get_model('sales', 'Product')
    ProductVariant = apps.get_model('sales', 'ProductVariant')

    for product in Product.objects.all():
        # Check if product has no variants
        if not product.variants.exists():
            # Create a default variant using old price/stock if available
            try:
                # Try to get price and stock from the product (old fields)
                price = getattr(product, 'price', None)
                stock = getattr(product, 'stock', None)

                if price is not None:
                    ProductVariant.objects.create(
                        product=product,
                        sku=f"{product.name[:3].upper()}-{product.id}-DEFAULT",
                        price=price,
                        stock=stock if stock is not None else 0,
                        is_active=True
                    )
            except Exception as e:
                print(f"Warning: Could not migrate product {product.id}: {e}")


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_coupon_order_discount_amount_category_order_coupon_and_more'),
    ]

    operations = [
        # First, migrate existing products to have variants
        migrations.RunPython(migrate_products_to_variants, migrations.RunPython.noop),

        # Remove old fields from Product model
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
    ]
